esphome:
  name: sprechanlage
  friendly_name: Sprechanlage

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprechanlage Fallback Hotspot"
    password: "XXXXXXXXXX"

captive_portal:
    

# Outputs of "Sprechanlage"
switch:
  - platform: gpio
    pin: D1
    name: "Türöffner"
    inverted: true
    id: door_opener
    icon: "mdi:door"
    on_turn_on:
      - output.turn_on: gpio_led
      - homeassistant.service:
          service: script.klingel_turoffner
      - delay: 2.5s
      - switch.turn_off: door_opener
      - output.turn_off: gpio_led

# Input Pins
binary_sensor:
  - platform: gpio
    pin: GPIO12
    id: optocopler_ring
    device_class: motion
    filters:
      - delayed_on: 30ms
      - delayed_off: 5s
    on_press:
      - output.turn_on: gpio_led
      - homeassistant.service:
          service: script.klingel_broadcast
      - delay: 0.5s
      - output.turn_off: gpio_led

# Status LED
light:
  - platform: status_led
    name: "Switch state"
    output: gpio_led

# Ouputs of GPIOs
output:
  - platform: gpio
    pin: GPIO2
    inverted: true
    id: gpio_led
